name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Generate the snake animation
        uses: Platane/snk@v2
        with:
          github_user_name: prasanna-collab  # Replace with your GitHub username
          outputs: dist/github-contribution-grid-snake.svg

      - name: Commit the snake animation
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          git add -A
          git commit -m "Updated the contribution grid snake"
          git push
