name: Generate Snake Animation

on:
  # Triggers the workflow every 6 hours to update the snake
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout the repository
        uses: actions/checkout@v2

      # Generate the snake animation
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: prasanna-collab  # Your GitHub username
          outputs: dist/snake.svg

      # Push the generated snake.svg to the output branch
      - name: Push Snake to the output branch
        uses: ad-m/github-push-action@v0.6.0
        with:
          branch: output  # Branch where the snake will be stored
          force: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
