name: Generate Snake Animation

on:
  schedule:
    # Runs at 12:00am UTC every day
    - cron: "0 0 * * *"
  workflow_dispatch: # Allows you to manually trigger the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout GitHub repo
        uses: actions/checkout@v2

      # Step 2: Generate the snake animation
      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: prasanna-collab  # Replace with your GitHub username
          outputs: dist/snake.svg

      # Step 3: Commit and push the snake animation file
      - name: Commit and push the snake animation
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Generated snake animation"
          git push
